config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :payments
  resources :categories
  resources :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  unauthenticated :users  do
    root 'users#index'
  end

  authenticated :users do
    root 'categories#index', as: :authenticated_root
    
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    # Define abilities for the user here. For example:
    if user.admin? :admin
      can :manage, :all
    else
      can :manage, Category, author_id: user.id
      can :manage, Payment, author_id: user.id
    end
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/categories_payment.rb
class CategoriesPayment < ApplicationRecord
  belongs_to :category
  belongs_to :payment
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_and_belongs_to_many :payments, dependent: :destroy

  validates :name, presence: true, length: { maximum: 250 }
  validates :icon, presence: true
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_and_belongs_to_many :categories

  validates :amount, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :name, presence: true, length: { maximum: 250 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories, dependent: :destroy, foreign_key: 'author_id'
  has_many :payments, dependent: :destroy, foreign_key: 'author_id'

  validates :name, presence: true, length: { maximum: 250 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    categories_path if resource.is_a?(User)
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation])
    # devise_parameter_sanitizer.permit(:account_update) do |u|
    #   u.permit(:name, :surname, :email, :password, :current_password)
    # end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = current_user.categories
  end

  def show
    @category = Category.find(params[:id])
    @payments = @category.payments.order(created_at: :desc)
  end

  def new
    @category = Category.new
  end

  def create
    if current_user.nil?
      redirect_to categories_path
      return
    end
    @category = Category.new(category_params)
    @category.author_id = current_user.id

    if @category.save
      flash[:success] = "'#{@category.name}' created successfully !!"
      redirect_to categories_path(user_id: current_user.id)
    else
      flash.now[:error] = "Couldn't create '#{@category.name} !!'"
      redirect_to new_user_category_path(current_user)
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def index
    @payments = Payment.all
  end

  def show; end

  def new
    @payment = Payment.new
    @categories = Category.where(author_id: current_user.id)
  end

  def create
    @category = Category.includes(:author).find(params[:category_id])
    @payment = current_user.payments.create(payment_params)
    @category.payments << @payment

    if @payment.save
      flash[:success] = "'#{@payment.name}' created successfully !!"
      redirect_to category_path(author_id: current_user.id, id: @category.id)
    else
      flash.now[:error] = "Couldn't create '#{@payment.name} !!'"
      redirect_to new_payment(current_user, @category.id)
    end
  end

  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to payment_url(@payment), notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_payment
    @payment = Payment.find(params[:id])
  end

  def payment_params
    params.require(:payment).permit(:name, :amount, :categories_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(created_at: :desc)
  end

  def home; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helpers.rb
module CategoriesHelpers
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
    <span><%= category.created_at.strftime("%Y/%m/%d") %></span>
  </p>

  <p>
    <strong>Icon:</strong>
    <%= category.icon %>
  </p>

  <div>
    <p class="math">Sum: $<%= category.payments.sum(:amount)%></p>
  </div>

</div>

app/views/categories/_form.html.erb
<div class="wblock">
  <div class="block">
    <%= form_with(model: category) do |form| %>
      <% if category.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

          <ul>
            <% category.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="">
        <%= form.text_field :name, class: 'catn', placeholder: 'Enter Category name' %>
      </div>
      <hr />
      <div class="">
        <%= form.text_field :icon, class: 'caticon', placeholder: 'Enter Icon image Url' %>
      </div>
      <br/>
      <div class="">
        <%= form.submit 'Add', class: 'submits' %>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/_header.html.erb
<header class="w-100 p-0 shadow mb-3 bg-body rounded">
    <div class="row text-bg-primary p-3">
      <div class="col m-1">
        <a href="/">
          <span class="material-symbols-outlined mt-2 badge text-bg-primary">
            arrow_back
            </span>
        </a>
      </div>
      <div class=" col m-1 d-flex flex-column align-items-center">
        <h3 class="mb-2 mt-2">CATEGORIES</h3>
      </div>
      <div class="col">
      </div>
    </div>
  </header>
  

app/views/categories/index.html.erb
<% if current_user %>
<div class="w-100">
  <header class="w-100 p-0 shadow mb-3 bg-body rounded fixed-top">
    <div class="row text-bg-primary p-3">
      <div class="col m-1">
        <a href="/">
          <span class="material-symbols-outlined mt-2 badge text-bg-primary">
            arrow_back
            </span>
        </a>
      </div>
      <div class=" col m-1 d-flex flex-column align-items-center">
        <h3 class="mb-2 mt-2">CATEGORIES</h3>
      </div>
      <div class="col">
      </div>
    </div>
  </header>

  <div class="p-5">
    <div class="">
      <% @categories.each do |category| %>
        <%= link_to category_path(category) do %>
          <div class="d-flex justify-content-between p-0 mb-2 shadow p-3 mb-3 bg-body rounded">
            <div class="">
              <img class="img-fluid rounded-start image" alt="category-logo" src=<%= category.icon %>>
            </div>
            <div class="d-flex aling-self-center mt-4 ">
              <h5 class=""><%= category.name %></h5>
            </div>  
            <div class="mt-4">
              <p class="sum">Total: $<%= category.payments.sum(:amount)%></p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>
</div>
<div class="btn fixed-bottom p-5">
  <%= link_to "Add New Category", new_category_path, class: "btn btn-success w-100" %>
</div>

app/views/categories/new.html.erb
<%= render "categories/header"%>
<%= render "form", category: @category %>

app/views/categories/show.html.erb
<%= render "payments/header" %>

<div class="d-flex flex-column justify-content-center align-items-center m-0 pt-0">
  <div class="w-100">
    <div class="d-flex justify-content-between p-2 shadow p-0 mb-2">
      <p>Total Amount:</p>
      <p>$<%= @category.payments.sum(:amount) %></p>
    </div>
  </div>

  <% @payments.each do |payment| %>
    <div class="d-flex flex-column justify-content-between p-2 mb-2 shadow p-3 mb-3 w-100">
      <div class="d-flex justify-content-between">
        <div>
          <p class=""><%= payment.name %></p>
          <p class="card-text"><small class="text-muted"><%= @category.created_at.strftime("%d/%m/%y") %></small></p>
        </div>
        <div>
          <p class="">$<%= payment.amount %></p>
        </div>
      </div>
    </div> 
  <% end %>


  <div class="fixed-bottom p-5">
    <%= link_to "Add New Transaction", new_payment_path(category_id: @category.id), class: "btn btn-success w-100" %>
  </div> 

</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-primary text-white fixed-top">
  <div class="container-fluid">
    <span class="navbar-brand mb-0 h1 text-white">MoneyChecker</span>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="" role="button" ><i class="fa fa-bars" aria-hidden="true" style="color:#e6e6ff"></i></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <%= link_to "Users", user_session_path, :class => 'nav-link text-white' %>
        <% if user_signed_in? %>
        <%= link_to "Categories", categories_path, :class => 'nav-link text-white' %>
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'nav-link text-white' %>
          <%= button_to "Logout", destroy_user_session_path, method: :delete, data: { turbo: false }, :class => 'btn btn-danger' %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'nav-link text-white' %>
          <%= link_to "Log in", new_user_session_path, :class => 'nav-link text-white' %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoneyChecker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
  
  <% if alert %>
    <p class="alert alert-success" role="alert">
      <%= alert %>
    </p>
  <% end %>  
  <% if notice %>
  <p class="alert alert-success" role="alert">
    <%= notice %>
  </p>
  <% end %>
  <div class="container">    
    <%= yield %>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  <%# <script src="assets/bootstrap.min.js"></script> %>
  </body>
</html>

app/views/payments/_form.html.erb
  <div class="d-flex pt-5">
    <%= form_with(model: payment, url: payments_url(category_id: category_id)) do |form| %>
      <% if payment.errors.any? %>
        <div class="">
          <h2><%= pluralize(payment.errors.count, "error") %>  this payment not allowed from being saved:</h2>

          <ul>
            <% payment.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      
      
      <form>
        <div class="form-outline mb-4 p-2 mt-2">
          <%= form.text_field :name, class: 'f-text', placeholder: 'Enter payment name', class:"form-control" %>
        </div>    
        <hr />
        <div class="form-outline mb-4">
          <%= form.number_field :amount, class: 'f-text', placeholder: 'Enter Amount', class:"form-control" %>
        </div>
        </br>
        <div class="btn btn-primary mt-2">
          <%= form.submit 'Add', class: 'btn btn-primary' %>
        </div>
      </form>
    <% end %>
  </div>

app/views/payments/_header.html.erb
<header class="w-100 p-0 shadow mb-3 bg-body rounded fixed-top">
    <div class="d-flex text-bg-primary p-3">
      <div class="col m-0">
        <%= link_to root_path do %>
          <span class="material-symbols-outlined mt-2 badge text-bg-primary">
            arrow_back
            </span>
        <% end %>
      </div>
      <div class=" col m-1 d-flex flex-column justify-content-center">
        <h3 class="mb-2 mt-2">TRANSACTIONS</h3>
      </div>
    </div>  
    <div class="d-flex justify-content-center text-bg-primary">
      <p class="">Most recent</p>
    </div>
</header>
  

app/views/payments/_new_header.html.erb
<header class="w-100 shadow mb-4 bg-body rounded fixed-top">
    <div class="d-flex text-bg-primary p-3">
      <div class="col m-0">
        <%= link_to root_path do %>
          <span class="material-symbols-outlined mt-2 badge text-bg-primary">
            arrow_back
            </span>
        <% end %>
      </div>
      <div class="col m-0 p-0 d-flex flex-column justify-content-center">
        <h3 class="mb-2 mt-2">NEW TRANSACTION</h3>
      </div>
    </div>  
    <div class="d-flex justify-content-center text-bg-primary">
      
    </div>
</header>

app/views/payments/_payment-header.html.erb
<header class="fixed-top">
  <div class="row">
    <div class="col m-1">
      <a href="/categories">
        <span class="material-symbols-outlined">
          arrow_back
          </span>
      </a>
    </div>
    <div class="col m-1 d-flex flex-column align-items-center">
      <h3 class="mb-0">Transactions</h3>
    </div>
    <div class="col">
    </div>
  </div>
</header>

app/views/payments/_payment.html.erb
<div id="<%= dom_id payment %>">
  <div class="payy"
    <p class="nam">
      <strong>Name: </strong>
      <%=  payment.name %>
    </p>

    <p>
      <strong>Amount: $</strong>
      <%= payment.amount %>
    </p>

    <p class="move">
      <%= link_to "Show", payment, class: 'move' %>
    </p>
  </div>
</div>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render "form", payment: @payment %>

<br>

<div>
  <%= link_to "Show this payment", @payment %> |
  <%= link_to "Back to payments", payments_path %>
</div>

app/views/payments/index.html.erb
<nav class="">
  <ul class="">
    <li>
    <%= link_to '<', categories_path, class: "" %>

    </li>
    <li>
      <h1 class="txt">ADD PAYMENTS</h1>
    </li>
    <li>
      <%= button_to 'LOG OUT', destroy_user_session_path, method: :delete, class: "" %>
    </li>
  </ul>
</nav>

<p style="color: green"><%= notice %></p>

<div class="payments">
  <% @payments.each do |payment| %>
    <%= render payment %>
  <% end %>
</div>

<div class="new-payment">
  <%= link_to "New payment", new_payment_path %>
</div>

app/views/payments/new.html.erb
<%= render "payments/new_header" %>

<%= render partial: "form", locals: { payment: @payment, category_id: params[:category_id] } %>

app/views/payments/show.html.erb
<div>
  
  <nav class="add-category">
    <ul class="a-category">
      <li>
        <%= link_to '<', payments_path, class: "arrow-left" %>
      </li>
      <li>
        <h1 class="t-details">Details</h1>
      </li>
      <li>
        <%= button_to 'Log out', destroy_user_session_path, method: :delete, class: "deletes" %>
      </li>
    </ul>
  </nav

  <p style="color: green"><%= notice %></p>

  <div class="">
    <div class="">
      <%= render @payment %>
    </div>
  </div>

  <div class="">
    <%= link_to "Back to categories", categories_path, class: "back" %>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'layouts/navbar' %>
<section class="form">
  </br>
  </br>
<<<<<<< HEAD
  </br>
  </br>
  </br>
  <%= render "badge" %> 
    <div class="d-flex flex-column fixed-bottom p-1">
=======
    <div class="d-flex flex-column fixed-bottom">
>>>>>>> 551a4ea47ac85795cee60e26ebd71bfb2eeb016e
      <button class="btn btn-success mb-1" type="button">
        <%= link_to "SIGN IN", new_user_session_path, class:"btn btn-success mb-1" %>
      </button>
      <button class="btn btn-secondary mb-4" type="button">
        <%= link_to "SIGN UP", new_user_registration_path, class:"btn btn-secondary mb-1" %>
      </button>
    </div>
</section>